### ISSUE TITLE
Remedial work

### ISSUE THREAD

**Issue by ckiss** [senecajs/seneca-twitter-auth#6]
- [x] update dependencies
- [x] update linting to match https://github.com/mirceaalexandru/seneca-local-auth
- [x] fix linting errors
- [x] remove any uneeded dependencies
- [x] Update license comment to match seneca-local-auth style
- [x] Add annotations as per seneca-local-auth
- [x] Update readme to say we have annotations like https://github.com/senecajs/seneca-rabbitmq-transport
- [x] add .gitignore like seneca-local-auth

**Comment by shanel262** [comment]
I've got this

**Comment by ghost** [comment]
Can this issue be closed?

**Comment by shanel262** [comment]
Yeah it can, I don't think I've permission to close it though @wprl
